# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f74d46b6659e355f083c1fad76c4de7530d98c698f7c82f137d5d490715be109bb85c1d56d09d68572e5b23058f232da5feca4b3c2088bf4cd0fab1d1521d05

test:
  secret_key_base: b7f47c746bfc3c6db9b3d93f3e55637e2af986c534d13654f836ae1800516afdb904a6fc3d911d405edc2922733e9cdfc2a379e17c92a73746ef40ccd99d3c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
